vich_uploader:
    db_driver: orm

    mappings:
        event_image:
            uri_prefix: /uploads/partners
            upload_destination: '%kernel.project_dir%/public/uploads/partners'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
