when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            # Depuis Symfony 7.3, ne pas fixer cette option est deprecie.
            collect_serializer_data: true
